export enum ActionType {
  REGISTER_SUCCESS = "REGISTER_SUCCESS",
  REGISTER_FAILURE = "REGISTER_FAILURE",
  SET_SUCCESS = "SET_SUCCESS",
  LOGIN_SUCCESS = "LOGIN_SUCCESS",
  LOGIN_FAILURE = "LOGIN_FAILURE",
  LOGOUT_SUCCESS = "LOGOUT_SUCCESS",
  LOGOUT_FAILURE = "LOGOUT_FAILURE",
  GET_USER_SUCCESS = "GET_USER_SUCCESS",
  GET_USER_FAILURE = "GET_USER_FAILURE",
  GET_USER_BY_ID_SUCCESS = "GET_USER_BY_ID_SUCCESS",
  GET_USER_BY_ID_FAILURE = "GET_USER_BY_ID_FAILURE",
}
